repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: poetry run isort
        args: ["--profile", "black", "--filter-files"]
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: poetry run black
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: poetry run flake8
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: poetry run mypy
        types: [python]
        pass_filenames: false

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: poetry run pytest
        types: [python]
        # pass_filenames: false

      - id: pytest-cov
        name: pytest + coverage
        stages: [push]
        language: system
        entry: poetry run pytest
        args:
          [
            --cov,
            # --cov-report term-missing,
            --cov-fail-under=100,
          ]
        types: [python]
        pass_filenames: false
        always_run: true

      - id: autoflake
        name: autoflake
        stages: [commit]
        language: system
        entry: poetry run autoflake
        args:
          [
            --in-place,
            --remove-all-unused-imports,
            --remove-unused-variables,
            --expand-star-imports,
            --ignore-init-module-imports,
          ]
        types: [python]

